parameters:
#    almot_App.example.class: Almot\AppBundle\Example

services:
#    almot_App.example:
#        class: %almot_App.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
